# Generated by Django 5.1.4 on 2025-01-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_answer_question_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
