# Generated by Django 5.1.4 on 2025-01-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_answer_update_at_alter_category_update_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="is_correct",
            new_name="iscorrect",
        ),
    ]
