# Generated by Django 5.1.4 on 2025-01-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_ans_question_alter_ans_update_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ans",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="myapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="update_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
